const playlist = {
    0: {
        src: "./assets/audio/Wayne.mp3", 
        artist: "Des Rocks",
        title: "Wayne",
        poster: "url(./assets/img/Wayne_poster.jpg)",
        backPoster: "./assets/img/Wayne_backposter.jpg",
    },
    1: {
        src: "./assets/audio/Rodina.mp3", 
        artist: "Анимация",
        title: "Родина",
        poster: "url(./assets/img/Rodina_poster.jpg)",
        backPoster: "./assets/img/Rodina_backposter.jpg",
    },
    2: {
        src: "./assets/audio/sky_in_fair.mp3", 
        artist: "5sta Family",
        title: "Небо в огне",
        poster: "url(./assets/img/SkyInFair_poster.jpg)",
        backPoster: "./assets/img/SkyInFair_backposter.jpg",
    },
    3: {
        src: "./assets/audio/Obitateli_raya.mp3", 
        artist: "Грот",
        title: "Обитатели рая",
        poster: "url(./assets/img/Grot_poster.jpg)",
        backPoster: "./assets/img/Grot_backposter.jpg",
    },
    4: {
        src: "./assets/audio/What_Are_You_Waiting_For.mp3", 
        artist: "Nickelback",
        title: "What are you waiting for",
        poster: "url(./assets/img/What_Are_You_Waiting_For_poster.jpg)",
        backPoster: "./assets/img/What_Are_You_Waiting_For_backposter.jpg",
    },
    5: {
        src: "./assets/audio/Inkvizitor_vsegda_prav.mp3", 
        artist: "DEEP-EX-SENSE",
        title: "Инквизитор всегда прав",
        poster: "url(./assets/img/deepexsense_poster.jpg)",
        backPoster: "./assets/img/deepexsense_backposter.jpg",
    },
    6: {
        src: "./assets/audio/If_Today_Was_Your_Last_Day.mp3", 
        artist: "Nickelback",
        title: "If today was your last day",
        poster: "url(./assets/img/if_today_was_your_last_day_poster.jpg)",
        backPoster: "./assets/img/if_today_was_your_last_day_poster.jpg",
    },
    7: {
        src: "./assets/audio/lullaby.mp3", 
        artist: "Oxxxymiron",
        title: "Колыбельная",
        poster: "url(./assets/img/oxy_poster.jpg)",
        backPoster: "./assets/img/oxy_backposter.jpg",
    },
    8: {
        src: "./assets/audio/Dean_Levis_-_Waves.mp3", 
        artist: "Dean Levis",
        title: "Waves",
        poster: "url(./assets/img/waves.jpg)",
        backPoster: "./assets/img/waves.jpg",
    },
    9: {
        src: "./assets/audio/Depeche_Mode_-_Enjoy_The_Silence.mp3", 
        artist: "Depeche Mode",
        title: "Enjoy The Silence",
        poster: "url(./assets/img/poster5.jpg)",
        backPoster: "./assets/img/poster5.jpg",
    },
    10: {
        src: "./assets/audio/Joan_Jett_and_the_Blackhearts_-_I_Hate_Myself_For_Loving_You.mp3", 
        artist: "Joan Jett and the Blackhearts",
        title: "I Hate Myself For Loving You",
        poster: "url(./assets/img/poster4.jpg)",
        backPoster: "./assets/img/poster4.jpg",
    },
    11: {
        src: "./assets/audio/Joan_Jett_And_The_Blackhearts_-_I_Love_Rock_N_Roll.mp3", 
        artist: "Joan Jett and the Blackhearts",
        title: "I Love Rock N Roll",
        poster: "url(./assets/img/poster4.jpg)",
        backPoster: "./assets/img/poster4.jpg",
    },
    12: {
        src: "./assets/audio/Joan_Jett_feat_Blackhearts_-_Bad_reputation.mp3", 
        artist: "Joan Jett and the Blackhearts",
        title: "Bad reputation",
        poster: "url(./assets/img/poster4.jpg)",
        backPoster: "./assets/img/poster4.jpg",
    },
    13: {
        src: "./assets/audio/Korol_i_SHut_-_Kukla_kolduna.mp3", 
        artist: "Король и шут",
        title: "Кукла колдуна",
        poster: "url(./assets/img/poster3.jpg)",
        backPoster: "./assets/img/poster3.jpg",
    },
    14: {
        src: "./assets/audio/Linkin_Park_-_In_The_End.mp3", 
        artist: "Linkin Park",
        title: "In The End",
        poster: "url(./assets/img/poster1.jpg)",
        backPoster: "./assets/img/poster1.jpg",
    },
    15: {
        src: "./assets/audio/NF_-_If_You_Want_Love.mp3", 
        artist: "NF",
        title: "If You Want Love",
        poster: "url(./assets/img/poster5.jpg)",
        backPoster: "./assets/img/poster5.jpg",
    },
    16: {
        src: "./assets/audio/NF_-_Let_You_Down.mp3", 
        artist: "NF",
        title: "Let You Down",
        poster: "url(./assets/img/poster5.jpg)",
        backPoster: "./assets/img/poster5.jpg",
    },
    17: {
        src: "./assets/audio/NF_Britt_Nicole_-_Can_You_Hold_Me_.mp3", 
        artist: "NF & Britt Nicole",
        title: "Can You Hold Me",
        poster: "url(./assets/img/poster5.jpg)",
        backPoster: "./assets/img/poster5.jpg",
    },
    18: {
        src: "./assets/audio/Voicians_-_Prayer.mp3", 
        artist: "Voicians",
        title: "Prayer",
        poster: "url(./assets/img/poster2.jpg)",
        backPoster: "./assets/img/poster2.jpg",
    },
    19: {
        src: "./assets/audio/Woodkid_Bruno_Bertoli_-_Run_Boy_Run.mp3", 
        artist: "Woodkid",
        title: "Run Boy Run",
        poster: "url(./assets/img/poster2.jpg)",
        backPoster: "./assets/img/poster2.jpg",
    },
    20: {
        src: "./assets/audio/Zemfira_-_KHochesh.mp3", 
        artist: "Zemfira",
        title: "Хочешь",
        poster: "url(./assets/img/poster4.jpg)",
        backPoster: "./assets/img/poster4.jpg",
    },
    21: {
        src: "./assets/audio/Lana_Del_Rey_-_Born_To_Die.mp3", 
        artist: "Lana_Del_Rey",
        title: "Born To Die",
        poster: "url(./assets/img/flowers.jpg)",
        backPoster: "./assets/img/flowers.jpg",
    },
    22: {
        src: "./assets/audio/Lana_Del_Rey_-_Video_Games.mp3", 
        artist: "Lana_Del_Rey",
        title: "Video Games",
        poster: "url(./assets/img/rose.jpg)",
        backPoster: "./assets/img/rose.jpg",
    },
    23: {
        src: "./assets/audio/The_Killers_-_Mr_Brightside.mp3", 
        artist: "The Killers",
        title: "Mr_Brightside",
        poster: "url(./assets/img/poster9.jpg)",
        backPoster: "./assets/img/poster9.jpg",
    },
    24: {
        src: "./assets/audio/Gotye_-_Somebody_That_I_Used_To_Know.mp3", 
        artist: "Gotye",
        title: "Somebody That I Used To Know",
        poster: "url(./assets/img/poster9.jpg)",
        backPoster: "./assets/img/poster9.jpg",
    },
    25: {
        src: "./assets/audio/Pink_Floyd_-_Another_Brick_In_The_Wall_Pt_2.mp3", 
        artist: "Pink Floyd",
        title: "Another Brick In The Wall",
        poster: "url(./assets/img/poster45.jpg)",
        backPoster: "./assets/img/poster45.jpg",
    },

}

export default playlist;